# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: itpir.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bitpir.proto\x12\x03pir\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x11IndexTreeResponse\x12\x10\n\x08idx_tree\x18\x01 \x01(\t\"\x1d\n\nPirRequest\x12\x0f\n\x07request\x18\x01 \x01(\x0c\"\x1f\n\x0bPirResponse\x12\x10\n\x08response\x18\x01 \x01(\x0c\x32{\n\x03Pir\x12\x32\n\x0bGetResponse\x12\x0f.pir.PirRequest\x1a\x10.pir.PirResponse\"\x00\x12@\n\x0cGetIndexTree\x12\x16.google.protobuf.Empty\x1a\x16.pir.IndexTreeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'itpir_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INDEXTREERESPONSE._serialized_start=49
  _INDEXTREERESPONSE._serialized_end=86
  _PIRREQUEST._serialized_start=88
  _PIRREQUEST._serialized_end=117
  _PIRRESPONSE._serialized_start=119
  _PIRRESPONSE._serialized_end=150
  _PIR._serialized_start=152
  _PIR._serialized_end=275
# @@protoc_insertion_point(module_scope)
