# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fhe_pir.fhe_pb2 as fhe__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class PirStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveContext = channel.stream_unary(
                '/pir.Pir/SaveContext',
                request_serializer=fhe__pb2.PirContext.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetResponse = channel.unary_unary(
                '/pir.Pir/GetResponse',
                request_serializer=fhe__pb2.PirRequest.SerializeToString,
                response_deserializer=fhe__pb2.PirResponse.FromString,
                )
        self.GetIndexTree = channel.unary_unary(
                '/pir.Pir/GetIndexTree',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=fhe__pb2.IndexTreeResponse.FromString,
                )


class PirServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveContext(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PirServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveContext': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveContext,
                    request_deserializer=fhe__pb2.PirContext.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResponse,
                    request_deserializer=fhe__pb2.PirRequest.FromString,
                    response_serializer=fhe__pb2.PirResponse.SerializeToString,
            ),
            'GetIndexTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexTree,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=fhe__pb2.IndexTreeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pir.Pir', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pir(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveContext(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/pir.Pir/SaveContext',
            fhe__pb2.PirContext.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pir.Pir/GetResponse',
            fhe__pb2.PirRequest.SerializeToString,
            fhe__pb2.PirResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIndexTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pir.Pir/GetIndexTree',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            fhe__pb2.IndexTreeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
